config/ident: Store large Regex object in a Box
Since regex 1.4.3 the `Regex` object becomes too large in comparison to
the other variant in `Ident`:

    error: large size difference between variants
    Error:   --> src/config/ident.rs:10:5
       |
    10 |     Pattern(Regex),
       |     ^^^^^^^^^^^^^^ this variant is 552 bytes
       |
       = note: `-D clippy::large-enum-variant` implied by `-D warnings`
    note: and the second-largest variant is 24 bytes:
      --> src/config/ident.rs:9:5
       |
    9  |     Name(String),
       |     ^^^^^^^^^^^^
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant

Also resolve the TODO by `Display`'ing the regex, which prints the
original expression.